name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  CI: true
  E2E_TRE_HOSTNAME: ${{secrets.E2E_TRE_HOSTNAME}}
  E2E_MITT3_HOSTNAME: ${{secrets.E2E_MITT3_HOSTNAME}}
  E2E_MITT3_USERNAME: ${{secrets.E2E_MITT3_USERNAME}}
  E2E_MITT3_PASSWORD: ${{secrets.E2E_MITT3_PASSWORD}}
  E2E_MITT3_AUTH_PAGE: ${{secrets.E2E_MITT3_AUTH_PAGE}}
jobs:
  playwright:
    name: "Playwright Tests -  Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run your tests
        run: pnpm run e2e -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
